version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: recetas_mysql_db
    restart: always

    environment:
      MYSQL_DATABASE: recetas_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: fastapi_app
    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    dns:
      - 8.8.8.8
      - 1.1.1.1

    volumes:
      - .:/proyecto

    depends_on:
      - db

volumes:
  db_data: